# These are supported funding model platforms

user1, user2, user3: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
Patreon1: # Replace with a single Patreon username
open_collective1: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tide-lift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge Vitality-longlasting-club 
liberapay1: # Replace with a single Liberapay username
issuehunt1: # Replace with a single IssueHunt username
otechie1: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding Vitality-longlasting-club
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
